# Generated by Django 3.0.6 on 2020-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=250)),
                ('blog_author', models.CharField(blank=True, max_length=40)),
                ('blog_date', models.DateTimeField()),
                ('blog_description', models.CharField(max_length=500)),
            ],
        ),
    ]
